// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"text/scanner"
	"time"
)

type Expression interface{}
type Token struct {
	token   int
	literal string
}

type VoidExpr struct{}

type StringExpr struct {
	literal string
}

type BoolInfixOpExpr struct {
	left     Expression
	operator rune
	right    Expression
}

type ProjectExpr struct {
	isAll bool
	name  string
}

type SectionExpr struct {
	name string
}

type LabelExpr struct {
	name string
}

type NotOpExpr struct {
	expr Expression
}

const (
	DUE_ON int = iota
	DUE_BEFORE
	DUE_AFTER
	NO_DUE_DATE
)

type DateExpr struct {
	operation int
	datetime  time.Time
	allDay    bool
}

func atoi(a string) (i int) {
	i, _ = strconv.Atoi(a)
	return
}

var now = time.Now
var today = func() time.Time {
	return time.Date(now().Year(), now().Month(), now().Day(), 0, 0, 0, 0, now().Location())
}
var timezone = func() *time.Location {
	return now().Location()
}

type yySymType struct {
	yys   int
	token Token
	expr  Expression
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault          = 57361
	yyEofCode          = 57344
	AFTER              = 57355
	BEFORE             = 57354
	DATE               = 57359
	DUE                = 57353
	LABELS             = 57360
	MONTH_IDENT        = 57348
	NO                 = 57358
	NUMBER             = 57347
	OVER               = 57356
	OVERDUE            = 57357
	STRING             = 57346
	TODAY_IDENT        = 57350
	TOMORROW_IDENT     = 57351
	TWELVE_CLOCK_IDENT = 57349
	YESTERDAY_IDENT    = 57352
	yyErrCode          = 57345

	yyMaxDepth = 200
	yyTabOfs   = -43
)

var (
	yyPrec = map[int]int{
		'&': 0,
		'|': 0,
	}

	yyXLAT = map[int]int{
		57344: 0,  // $end (39x)
		38:    1,  // '&' (38x)
		124:   2,  // '|' (38x)
		41:    3,  // ')' (37x)
		57347: 4,  // NUMBER (23x)
		57346: 5,  // STRING (13x)
		57348: 6,  // MONTH_IDENT (8x)
		57374: 7,  // s_time (8x)
		47:    8,  // '/' (7x)
		57353: 9,  // DUE (7x)
		57364: 10, // s_date (7x)
		57365: 11, // s_date_year (7x)
		57366: 12, // s_datetime (7x)
		57350: 13, // TODAY_IDENT (7x)
		57351: 14, // TOMORROW_IDENT (7x)
		57352: 15, // YESTERDAY_IDENT (7x)
		35:    16, // '#' (6x)
		33:    17, // '!' (5x)
		40:    18, // '(' (5x)
		58:    19, // ':' (5x)
		64:    20, // '@' (5x)
		57362: 21, // expr (5x)
		57358: 22, // NO (5x)
		57356: 23, // OVER (5x)
		57357: 24, // OVERDUE (5x)
		57367: 25, // s_label_key (5x)
		57368: 26, // s_no_labels (5x)
		57369: 27, // s_nodate (5x)
		57370: 28, // s_overdue (5x)
		57371: 29, // s_project_all_key (5x)
		57372: 30, // s_project_key (5x)
		57373: 31, // s_section_key (5x)
		57359: 32, // DATE (2x)
		57349: 33, // TWELVE_CLOCK_IDENT (2x)
		57355: 34, // AFTER (1x)
		57354: 35, // BEFORE (1x)
		57363: 36, // filter (1x)
		57360: 37, // LABELS (1x)
		57361: 38, // $default (0x)
		57345: 39, // error (0x)
	}

	yySymNames = []string{
		"$end",
		"'&'",
		"'|'",
		"')'",
		"NUMBER",
		"STRING",
		"MONTH_IDENT",
		"s_time",
		"'/'",
		"DUE",
		"s_date",
		"s_date_year",
		"s_datetime",
		"TODAY_IDENT",
		"TOMORROW_IDENT",
		"YESTERDAY_IDENT",
		"'#'",
		"'!'",
		"'('",
		"':'",
		"'@'",
		"expr",
		"NO",
		"OVER",
		"OVERDUE",
		"s_label_key",
		"s_no_labels",
		"s_nodate",
		"s_overdue",
		"s_project_all_key",
		"s_project_key",
		"s_section_key",
		"DATE",
		"TWELVE_CLOCK_IDENT",
		"AFTER",
		"BEFORE",
		"filter",
		"LABELS",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {36, 0},
		2:  {36, 1},
		3:  {21, 3},
		4:  {21, 3},
		5:  {21, 1},
		6:  {21, 2},
		7:  {21, 2},
		8:  {21, 2},
		9:  {21, 2},
		10: {21, 1},
		11: {21, 3},
		12: {21, 2},
		13: {21, 1},
		14: {21, 1},
		15: {21, 4},
		16: {21, 4},
		17: {21, 1},
		18: {29, 2},
		19: {30, 1},
		20: {31, 1},
		21: {25, 1},
		22: {26, 2},
		23: {27, 2},
		24: {27, 3},
		25: {28, 2},
		26: {28, 1},
		27: {12, 2},
		28: {12, 1},
		29: {12, 1},
		30: {11, 5},
		31: {11, 3},
		32: {11, 3},
		33: {11, 1},
		34: {11, 1},
		35: {11, 1},
		36: {11, 1},
		37: {10, 2},
		38: {10, 2},
		39: {10, 3},
		40: {7, 3},
		41: {7, 5},
		42: {7, 2},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [67][]uint8{
		// 0
		{42, 4: 66, 46, 67, 65, 59, 56, 68, 64, 57, 69, 70, 71, 58, 53, 52, 20: 60, 45, 61, 62, 63, 50, 51, 55, 54, 48, 47, 49, 36: 44},
		{43},
		{41, 101, 100},
		{38, 38, 38, 38},
		{5: 109},
		// 5
		{5: 108},
		{5: 107},
		{5: 106},
		{33, 33, 33, 33},
		{4: 66, 46, 67, 65, 59, 56, 68, 64, 57, 69, 70, 71, 58, 53, 52, 20: 60, 104, 61, 62, 63, 50, 51, 55, 54, 48, 47, 49},
		// 10
		{4: 66, 46, 67, 65, 59, 56, 68, 64, 57, 69, 70, 71, 58, 53, 52, 20: 60, 99, 61, 62, 63, 50, 51, 55, 54, 48, 47, 49},
		{30, 30, 30, 30},
		{29, 29, 29, 29},
		{34: 94, 93},
		{26, 26, 26, 26},
		// 15
		{5: 24, 16: 92},
		{5: 23},
		{5: 22},
		{9: 90, 32: 89, 37: 88},
		{9: 87},
		// 20
		{17, 17, 17, 17},
		{15, 15, 15, 15, 86, 7: 85},
		{14, 14, 14, 14},
		{6: 75, 8: 74, 19: 76, 33: 77},
		{4: 72},
		// 25
		{10, 10, 10, 10, 10},
		{9, 9, 9, 9, 9},
		{8, 8, 8, 8, 8},
		{7, 7, 7, 7, 7},
		{6, 6, 6, 6, 73},
		// 30
		{12, 12, 12, 12, 12},
		{4: 82},
		{5, 5, 5, 5, 81},
		{4: 78},
		{1, 1, 1, 1},
		// 35
		{3, 3, 3, 3, 19: 79},
		{4: 80},
		{2, 2, 2, 2},
		{11, 11, 11, 11, 11},
		{4, 4, 4, 4, 4, 8: 83},
		// 40
		{4: 84},
		{13, 13, 13, 13, 13},
		{16, 16, 16, 16},
		{19: 76, 33: 77},
		{18, 18, 18, 18},
		// 45
		{21, 21, 21, 21},
		{20, 20, 20, 20},
		{32: 91},
		{19, 19, 19, 19},
		{5: 25},
		// 50
		{19: 97},
		{19: 95},
		{4: 66, 6: 67, 65, 10: 68, 64, 96, 69, 70, 71},
		{27, 27, 27, 27},
		{4: 66, 6: 67, 65, 10: 68, 64, 98, 69, 70, 71},
		// 55
		{28, 28, 28, 28},
		{31, 101, 100, 31},
		{4: 66, 46, 67, 65, 59, 56, 68, 64, 57, 69, 70, 71, 58, 53, 52, 20: 60, 103, 61, 62, 63, 50, 51, 55, 54, 48, 47, 49},
		{4: 66, 46, 67, 65, 59, 56, 68, 64, 57, 69, 70, 71, 58, 53, 52, 20: 60, 102, 61, 62, 63, 50, 51, 55, 54, 48, 47, 49},
		{39, 39, 39, 39},
		// 60
		{40, 40, 40, 40},
		{1: 101, 100, 105},
		{32, 32, 32, 32},
		{34, 34, 34, 34},
		{35, 35, 35, 35},
		// 65
		{36, 36, 36, 36},
		{37, 37, 37, 37},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 39

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yyVAL.expr = VoidExpr{}
		}
	case 2:
		{
			yyVAL.expr = yyS[yypt-0].expr
			yylex.(*Lexer).result = yyVAL.expr
		}
	case 3:
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyS[yypt-2].expr, operator: '|', right: yyS[yypt-0].expr}
		}
	case 4:
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyS[yypt-2].expr, operator: '&', right: yyS[yypt-0].expr}
		}
	case 5:
		{
			yyVAL.expr = StringExpr{literal: yyS[yypt-0].token.literal}
		}
	case 6:
		{
			yyVAL.expr = ProjectExpr{isAll: false, name: yyS[yypt-0].token.literal}
		}
	case 7:
		{
			yyVAL.expr = ProjectExpr{isAll: true, name: yyS[yypt-0].token.literal}
		}
	case 8:
		{
			yyVAL.expr = SectionExpr{name: yyS[yypt-0].token.literal}
		}
	case 9:
		{
			yyVAL.expr = LabelExpr{name: yyS[yypt-0].token.literal}
		}
	case 10:
		{
			yyVAL.expr = LabelExpr{name: ""}
		}
	case 11:
		{
			yyVAL.expr = yyS[yypt-1].expr
		}
	case 12:
		{
			yyVAL.expr = NotOpExpr{expr: yyS[yypt-0].expr}
		}
	case 13:
		{
			yyVAL.expr = DateExpr{allDay: false, datetime: now(), operation: DUE_BEFORE}
		}
	case 14:
		{
			yyVAL.expr = DateExpr{operation: NO_DUE_DATE}
		}
	case 15:
		{
			e := yyS[yypt-0].expr.(DateExpr)
			e.operation = DUE_BEFORE
			yyVAL.expr = e
		}
	case 16:
		{
			e := yyS[yypt-0].expr.(DateExpr)
			e.operation = DUE_AFTER
			yyVAL.expr = e
		}
	case 18:
		{
			yyVAL.expr = yyS[yypt-1].token
		}
	case 19:
		{
			yyVAL.expr = yyS[yypt-0].token
		}
	case 20:
		{
			yyVAL.expr = yyS[yypt-0].token
		}
	case 21:
		{
			yyVAL.expr = yyS[yypt-0].token
		}
	case 22:
		{
			yyVAL.expr = yyS[yypt-1].token
		}
	case 23:
		{
			yyVAL.expr = yyS[yypt-1].token
		}
	case 24:
		{
			yyVAL.expr = yyS[yypt-2].token
		}
	case 25:
		{
			yyVAL.expr = yyS[yypt-1].token
		}
	case 26:
		{
			yyVAL.expr = yyS[yypt-0].token
		}
	case 27:
		{
			date := yyS[yypt-1].expr.(time.Time)
			time := yyS[yypt-0].expr.(time.Duration)
			yyVAL.expr = DateExpr{allDay: false, datetime: date.Add(time)}
		}
	case 28:
		{
			yyVAL.expr = DateExpr{allDay: true, datetime: yyS[yypt-0].expr.(time.Time)}
		}
	case 29:
		{
			nd := now().Sub(today())
			d := yyS[yypt-0].expr.(time.Duration)
			if d <= nd {
				d = d + time.Duration(int64(time.Hour)*24)
			}
			yyVAL.expr = DateExpr{allDay: false, datetime: today().Add(d)}
		}
	case 30:
		{
			yyVAL.expr = time.Date(atoi(yyS[yypt-0].token.literal), time.Month(atoi(yyS[yypt-4].token.literal)), atoi(yyS[yypt-2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 31:
		{
			yyVAL.expr = time.Date(atoi(yyS[yypt-0].token.literal), MonthIdentHash[strings.ToLower(yyS[yypt-2].token.literal)], atoi(yyS[yypt-1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 32:
		{
			yyVAL.expr = time.Date(atoi(yyS[yypt-0].token.literal), MonthIdentHash[strings.ToLower(yyS[yypt-1].token.literal)], atoi(yyS[yypt-2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 33:
		{
			tod := today()
			date := yyS[yypt-0].expr.(time.Time)
			if date.Before(tod) {
				date = date.AddDate(1, 0, 0)
			}
			yyVAL.expr = date
		}
	case 34:
		{
			yyVAL.expr = today()
		}
	case 35:
		{
			yyVAL.expr = today().AddDate(0, 0, 1)
		}
	case 36:
		{
			yyVAL.expr = today().AddDate(0, 0, -1)
		}
	case 37:
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyS[yypt-1].token.literal)], atoi(yyS[yypt-0].token.literal), 0, 0, 0, 0, timezone())
		}
	case 38:
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyS[yypt-0].token.literal)], atoi(yyS[yypt-1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 39:
		{
			yyVAL.expr = time.Date(now().Year(), time.Month(atoi(yyS[yypt-0].token.literal)), atoi(yyS[yypt-2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 40:
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyS[yypt-2].token.literal)) + int64(time.Minute)*int64(atoi(yyS[yypt-0].token.literal)))
		}
	case 41:
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyS[yypt-4].token.literal)) + int64(time.Minute)*int64(atoi(yyS[yypt-2].token.literal)) + int64(time.Second)*int64(atoi(yyS[yypt-0].token.literal)))
		}
	case 42:
		{
			hour := atoi(yyS[yypt-1].token.literal)
			if TwelveClockIdentHash[yyS[yypt-0].token.literal] {
				hour = hour + 12
			}
			yyVAL.expr = time.Duration(int64(time.Hour) * int64(hour))
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

type Lexer struct {
	scanner.Scanner
	result Expression
}

var MonthIdentHash = map[string]time.Month{
	"jan":  time.January,
	"feb":  time.February,
	"mar":  time.March,
	"apr":  time.April,
	"may":  time.May,
	"june": time.June,
	"july": time.July,
	"aug":  time.August,
	"sept": time.September,
	"oct":  time.October,
	"nov":  time.November,
	"dec":  time.December,

	"january":   time.January,
	"february":  time.February,
	"march":     time.March,
	"april":     time.April,
	"august":    time.August,
	"september": time.September,
	"october":   time.October,
	"november":  time.November,
	"december":  time.December,
}

var TwelveClockIdentHash = map[string]bool{
	"am": false,
	"pm": true,
}

var TodayIdentHash = map[string]bool{
	"today": true,
	"tod":   true,
}

var TomorrowIdentHash = map[string]bool{
	"tomorrow": true,
	"tom":      true,
}

var OverDueHash = map[string]bool{
	"overdue": true,
	"od":      true,
}

func (l *Lexer) Lex(lval *yySymType) int {
	token := int(l.Scan())
	switch token {
	case scanner.Ident:
		lowerToken := strings.ToLower(l.TokenText())
		if _, ok := MonthIdentHash[lowerToken]; ok {
			token = MONTH_IDENT
		} else if _, ok := TwelveClockIdentHash[lowerToken]; ok {
			token = TWELVE_CLOCK_IDENT
		} else if _, ok := TodayIdentHash[lowerToken]; ok {
			token = TODAY_IDENT
		} else if _, ok := TomorrowIdentHash[lowerToken]; ok {
			token = TOMORROW_IDENT
		} else if lowerToken == "yesterday" {
			token = YESTERDAY_IDENT
		} else if lowerToken == "due" {
			token = DUE
		} else if lowerToken == "before" {
			token = BEFORE
		} else if lowerToken == "after" {
			token = AFTER
		} else if lowerToken == "over" {
			token = OVER
		} else if _, ok := OverDueHash[lowerToken]; ok {
			token = OVERDUE
		} else if lowerToken == "no" {
			token = NO
		} else if lowerToken == "date" {
			token = DATE
		} else if lowerToken == "labels" {
			token = LABELS
		} else {
			token = STRING
		}
	case scanner.Int:
		token = NUMBER
	}
	lval.token = Token{token: token, literal: l.TokenText()}
	return token
}

func (l *Lexer) Error(e string) {
	fmt.Fprintf(os.Stderr, "Filter error: %s \nFor proper filter syntax see https://support.todoist.com/hc/en-us/articles/205248842-Filters\n", e)
	os.Exit(1)
}

func Filter(f string) (e Expression) {
	l := new(Lexer)
	l.Init(strings.NewReader(f))
	yyParse(l)
	return l.result
}
